version: '3.8'

services:
  db:
    image: postgres:17
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: damdar
      POSTGRES_DB: mco_db
    ports:
      - "1000:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
